### ISSUE TITLE
Python multiprocessing error

### ISSUE THREAD

**Issue by adrastee** [s77rt/multicapconverter#2]
Hi,
Error below, on Windows 10 + Python 3.8.0

> c:\Python38\python.exe multicapconverter.py -i handshakes.cap --group-by handshake -x hccapx
> Networks detected: 8
> Traceback (most recent call last):
>   File "multicapconverter.py", line 1685, in <module>
>     main()
>   File "multicapconverter.py", line 1590, in main
>     build(export=args.export, export_unauthenticated=args.all, filters=args.filter_by, group_by=args.group_by)
>   File "multicapconverter.py", line 1541, in build
>     task.start()
>   File "c:\Python38\lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "c:\Python38\lib\multiprocessing\context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "c:\Python38\lib\multiprocessing\context.py", line 326, in _Popen
>     return Popen(process_obj)
>   File "c:\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
>     reduction.dump(process_obj, to_child)
>   File "c:\Python38\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'build.<locals>.build_chunk'

**Comment by s77rt** [comment]
@adrastee 
Thanks for the report
Issue is fixed now.

**Comment by adrastee** [comment]
Thanks! I confirm it works OK.
