### ISSUE TITLE
Get PMKIDs also from other frames

### ISSUE THREAD

**Issue by adrastee** [s77rt/multicapconverter#3]
Hi,
I have a cap file where multicapconverter does not output any PMIKD while hcxpcapngtool does find one.

So here is a feature request to get PMKIDs also from other frames (e.g. reassociationrequest)
Output: https://pastebin.com/L49uNT1S

I can provide cap file by email if you want.

Thanks a lot !

**Comment by s77rt** [comment]
Hi @adrastee, 
Thanks for the report, 
Kindly provide the cap file, i will check that..

**Comment by ZerBea** [comment]
We can expect PMKIDs additional to EAPOL M1 frames in associationrequest frames (rare), reassociationrequest frames and EAPOL M2 frames.

**Comment by s77rt** [comment]
@ZerBea 
multicapconveter extract pmkid only from EAPOL M1, associationrequest, reassociationrequest frames.
I will add EAPOL M2. if you can provide a cap that have a pmkid in this frame it would be much helpful

**Comment by ZerBea** [comment]
Please check you gmail.

**Comment by s77rt** [comment]
@ZerBea 
Got it, thanks!
I have added the "Extract PMKIDs from EAPOL-M2" Feature.

Waiting @adrastee confirmation..

**Comment by ZerBea** [comment]
It's important to check AK suite in RSN-IE, too. Only PSK and PSK256 are PBKFDF2 related. All others not. I'm working on this...

**Comment by s77rt** [comment]
@ZerBea 

For EAPOL-M1:

- Check: Key Descriptor Version: AES Cipher, HMAC-SHA1 MIC (2)

For EAPOL-M2, associationrequest and reassociationrequest:

- Check: Key Descriptor Version: AES Cipher, HMAC-SHA1 MIC (2)
- Check: AKM SUITE

Key Descriptor Version CHECK: https://github.com/s77rt/multicapconverter/blob/master/multicapconverter.py#L1042 and https://github.com/s77rt/multicapconverter/blob/master/multicapconverter.py#L1046
AKM SUITE CHECK: https://github.com/s77rt/multicapconverter/blob/master/multicapconverter.py#L649-L655

**Comment by ZerBea** [comment]
Great. You think of everything.

**Comment by adrastee** [comment]
Hi,
Thanks!
But It's still the same output.
Version 0.1.3.
No PMKID WPA*01*

**Comment by s77rt** [comment]
@adrastee 
I got your capture file, the pmkid is being extracted, but not exported for somereason.. I'm checking this currently..
(I will update you soon)

**Comment by s77rt** [comment]
@adrastee 
Okay, I found the problem.
In the capture you sent me, the station that have a relation with the pmkid, does not have any other M1,M2,M3,M4 frames captures. (thus the DB.excpkt_add operation never occurs, and we relay on the list of excpkts when building/exporting)

This will be fixed..

**Comment by adrastee** [comment]
Interesting case!
Thanks for your time.

**Comment by s77rt** [comment]
Fixed.
Can you try now?

**Comment by adrastee** [comment]
Awesome, it works great! Thanks!
